version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gocognit
    - nolintlint
    - varnamelen
    - wsl
    - wsl_v5
    - funcorder
  settings:
    govet:
      disable:
        - composites
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - goconst
      - linters:
          - goconst
        text: "string `(_id|name|size|count|avgObjSize|\
            collation|createIndexes|indexes|collMod|index|\
            \\$_id|\\$project|\\$set|\\$unset|\\$push|\\$each|\\$slice)`"
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
