linters:
  enable-all: true
  disable:
    - nolintlint
    - gci
    - contextcheck
    - exhaustruct
    - depguard
    - varnamelen
    - cyclop
    - gocognit
    - dupl
    - funlen
    - tenv
    - wsl

linters-settings:
  govet:
    disable:
      - composites
  misspell:
    locale: "US"
