version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gocognit
    - nestif
    - nolintlint
    - varnamelen
    - wsl
    - wsl_v5
    - funcorder
  settings:
    govet:
      disable:
        - composites
    misspell:
      locale: US
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
