#!/usr/bin/env bash

docker run -d \
    --name rs00 \
    --hostname rs00 \
    -p 30000:30000 \
    mongo:8 --port=30000 --replSet=rs0 --bind_ip_all

while ! mongosh "mongodb://rs00:30000" --quiet --eval "db.version()" >/dev/null 2>&1; do sleep 0.5; done
mongosh "mongodb://rs00:30000" --quiet --eval 'disableTelemetry()'
mongosh "mongodb://rs00:30000" --quiet --eval 'rs.initiate()'
