#!/usr/bin/env bash

SBASE=$(dirname "$0")

# shellcheck source=/dev/null
source "$SBASE/util"

export compose="$SBASE/compose.yml"


# https://www.mongodb.com/docs/v7.0/tutorial/deploy-sharded-cluster-with-keyfile-access-control/
if [ ! -s "$SBASE/mongo/keyFile" ]; then
    echo >&2 generate "$SBASE/mongo/keyFile"
    openssl rand -base64 756 >"$SBASE/mongo/keyFile"
    chmod 400 "$SBASE/mongo/keyFile"
fi

dcf up -d rs00 rs01 rs02 rs10 rs11 rs12

mwait "rs00:30000"
mwait "rs01:30001"
mwait "rs02:30002"

rsinit "rs0" "rs00:30000"

mwait "rs10:30100"
mwait "rs11:30101"
mwait "rs12:30102"

rsinit "rs1" "rs10:30100"
