services:
  rs00:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs00
    hostname: rs00
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50000:50000"]
    volumes: ["rs00:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs0",
        "--port=50000",
      ]

  rs01:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs01
    hostname: rs01
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50001:50001"]
    volumes: ["rs01:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs0",
        "--port=50001",
      ]

  rs02:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs02
    hostname: rs02
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50002:50002"]
    volumes: ["rs02:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs0",
        "--port=50002",
      ]

  rs10:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs10
    hostname: rs10
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50100:50100"]
    volumes: ["rs10:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs1",
        "--port=50100",
      ]

  rs11:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs11
    hostname: rs11
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50101:50101"]
    volumes: ["rs11:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs1",
        "--port=50101",
      ]

  rs12:
    image: "percona/percona-server-mongodb:${MONGO_VERSION:-8.0}"
    container_name: rs12
    hostname: rs12
    mem_limit: 2g
    memswap_limit: 2g
    ports: ["50102:50102"]
    volumes: ["rs12:/data/db", "./mongo/:/cfg:ro"]
    command:
      [
        "-f",
        "/cfg/mongod.conf",
        "--replSet=rs1",
        "--port=50102",
      ]

volumes:
  rs00:
  rs01:
  rs02:
  rs10:
  rs11:
  rs12:
