name: reviewdog

on: [pull_request]

jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          locale: "US"

  alex:
    name: alex
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: alex
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
