name: reviewdog
on: [pull_request]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: spellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          locale: "US"

  alex:
    name: runner / alex
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: alex
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
