name: reviewdog
on: [pull_request]
jobs:
  gofmt:
    name: runner / gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go install golang.org/x/tools/cmd/goimports@latest
      - run: go install mvdan.cc/gofumpt@latest
      - run: goimports -w -local "github.com/percona" .
      - run: gofumpt -w -extra .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          level: error

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: spellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          reporter: github-pr-review
          locale: "US"

  alex:
    name: runner / alex
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.changed_files < 301 }}
    steps:
      - uses: actions/checkout@v4
      - name: alex
        uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-review
