name: Scan

on: [pull_request]

permissions:
  contents: read

jobs:
  scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Generate SBOM
        # v0.36.0
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: fs
          scan-ref: .
          format: cyclonedx
          output: sbom.json
          version: v0.72.0

      - name: Run trivy scan on SBOM
        # v0.36.0
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          scan-type: sbom
          scan-ref: sbom.json
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: '1'
          # Reuse the Trivy binary installed by the SBOM generation step.
          skip-setup-trivy: true
